# Generated by Django 3.0.7 on 2020-08-24 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0002_auto_20200824_0402'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferences',
            name='meeting_area',
            field=models.CharField(max_length=100, null=True, verbose_name='会议地点'),
        ),
        migrations.AddField(
            model_name='periodical',
            name='page_count',
            field=models.CharField(max_length=20, null=True, verbose_name='总页数'),
        ),
        migrations.AddField(
            model_name='periodical',
            name='page_numbers',
            field=models.CharField(max_length=20, null=True, verbose_name='页码'),
        ),
    ]
