# Generated by Django 3.0.7 on 2020-08-24 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0003_auto_20200824_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patent',
            name='application_date',
            field=models.DateField(null=True, verbose_name='专利申请日期'),
        ),
        migrations.AlterField(
            model_name='patent',
            name='publication_date',
            field=models.DateField(null=True, verbose_name='专利公告日期'),
        ),
    ]
