# Generated by Django 3.0.7 on 2020-08-24 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0004_auto_20200824_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodical',
            name='periodical_number',
            field=models.CharField(max_length=30, null=True, verbose_name='卷'),
        ),
    ]
