# Generated by Django 3.0.7 on 2020-08-24 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0005_auto_20200824_0709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodical',
            name='doi',
            field=models.CharField(db_index=True, max_length=100, null=True, unique=True, verbose_name='doi'),
        ),
    ]
