# Generated by Django 3.0.7 on 2020-08-24 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0009_auto_20200824_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferences',
            name='page',
            field=models.CharField(max_length=20, null=True, verbose_name='页码'),
        ),
    ]
