# Generated by Django 3.0.7 on 2020-09-08 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0014_auto_20200826_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionrecord',
            name='action',
            field=models.CharField(max_length=100, verbose_name='动作'),
        ),
        migrations.AlterField(
            model_name='actionrecord',
            name='description',
            field=models.TextField(null=True, verbose_name='用户操作说明'),
        ),
        migrations.AlterField(
            model_name='actionrecord',
            name='ip',
            field=models.CharField(max_length=100, null=True, verbose_name='用户ip'),
        ),
        migrations.AlterField(
            model_name='actionrecord',
            name='terminal',
            field=models.CharField(max_length=100, null=True, verbose_name='操作使用的终端'),
        ),
    ]
