# Generated by Django 3.0.7 on 2020-08-24 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0008_auto_20200824_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='category',
            field=models.CharField(max_length=40, null=True, verbose_name='中图分类'),
        ),
    ]
