# Generated by Django 3.0.7 on 2020-08-26 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0011_auto_20200824_0753'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Conferences',
            new_name='Conference',
        ),
    ]
